spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
spring.datasource.username=test
spring.datasource.password=test

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto = validate

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE

spring.liquibase.change-log=classpath:db/changelog.xml

jwt.issuer=Vet-Care
jwt.access.signing.key=SSCDmDGBSZmgcn4oVBv81VSqgIgezncVj4mrTskNyqC
jwt.refresh.signing.key=hw046WWnFDQxju5YEwfPG9URmATbRJEMpVnOcx62LoA
jwt.cookie.life.time=30m
access.token.life.time=15m
refresh.token.life.time=30m

max.failed.attempts=10
lock.duration.minutes=60

holiday.calendar=POLAND